on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: fix permissions
      run: chmod +x build.sh
    - name: run build script
      run: sudo bash build.sh -f -a arm64
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: kali-arm64-rebuild-latest.tar.xz
        path : output/kali-arm64-rebuild-latest.tar.xz