on: [push]

jobs:
  build:

    runs-on: kalilinux/kali-rolling
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: run build script
      run: build.sh -f -a arm64
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: kali-arm64-rebuild-latest.tar.gz
        path : fs/kali-arm64/kali-arm64-rebuild-latest.tar.gz