on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: fix permissions
      run: chmod +x build.sh
    - name: run build script
      run: sudo bash build.sh -f -a armhf
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: kali-arm64-rebuild-latest.tar.xz
        path : /home/runner/work/kali-fs-builder/kali-fs-builder/output/kalifs-armhf-full.tar.xz